spring.application.name=autentication
spring.data.mongodb.uri=mongodb+srv://onofrebernalsantiago:ddAtaOXq710NihdF@cluster0.o4dymmg.mongodb.net/
spring.data.mongodb.database=loginDB
server.port=8080
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp